global:
  resolve_timeout: 1m

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#alertas'
        send_resolved: true
        api_url: 'https://hooks.slack.com/services/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'
        title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
        text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"

